// react_project/src/views/FormView.js
import { useEffect, useState } from "react";
import DataForm from "../components/dataform/DataForm";

export default function FormView() {
    const [submitted, setSubmitted] = useState({});
    const [submissionCount, setSubmissionCount] = useState(0)

    useEffect(() => {
        if (submitted.firstname !== undefined
            && submitted.lastname !== undefined
            && submitted.age !== undefined) {
            setSubmissionCount(submissionCount + 1);
        }
    }, [submitted]);

    return (
        <>
            <h1>Formulaire:</h1>
            <DataForm onSubmit={setSubmitted} />
            <h1>Donnees soumises:</h1>
            <p>Nom: {submitted.lastname}</p>
            <p>Prenom: {submitted.firstname}</p>
            <p>Age: {submitted.age}</p>
            <p>Nombre de soumissions: {submissionCount}</p>
        </>
    );
}

// vue_project/src/views/FormView.vue
<script setup>
import DataForm from "../components/DataForm.vue";
import { ref, watch } from "vue";

const submitted = ref({});
const submissionCount = ref(0);

watch(submitted, async (newValue, oldValue) => {
    if (submitted.value.firstname !== undefined
        && submitted.value.lastname !== undefined
        && submitted.value.age !== undefined) {
        submissionCount.value++;
    }
});
</script>

<template>
    <h1>Formulaire:</h1>
    <DataForm :onSubmit="(res) => submitted = res" />
    <h1>Donnees soumises:</h1>
    <p>Nom: {{ submitted.lastname }}</p>
    <p>Prenom: {{ submitted.firstname }}</p>
    <p>Age: {{ submitted.age }}</p>
    <p>Nombre de soumissions: {{ submissionCount }}</p>
</template>

<style scoped>

</style>
